steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', "eu.gcr.io/$PROJECT_ID/magento2-php72:$SHORT_SHA", '-f', 'k8s-config/php-docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "eu.gcr.io/$PROJECT_ID/magento2-php72:$SHORT_SHA"]
# Run pre-release actions
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#   - run
#   - --filename=k8s-config/pre-release-actions.yml
#   - --image=eu.gcr.io/$PROJECT_ID/magento2-php72:$SHORT_SHA
#   - --location=${_CLOUDSDK_COMPUTE_ZONE}
#   - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
# deploy containers to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=k8s-config/apache-php.yml
  - --image=eu.gcr.io/$PROJECT_ID/magento2-php72:$SHORT_SHA
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  timeout: 1000s
timeout: 1500s