steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker build -t eu.gcr.io/$PROJECT_ID/magento2-apache24:latest -f k8s-config/apache-docker/Dockerfile --build-arg WEB_SSL_KEY=$$SSL_KEY --build-arg WEB_SSL_CRT=$$SSL_CRT --build-arg WEB_SSL_PEM=$$SSL_PEM .'
    ]
  secretEnv: ['SSL_KEY','SSL_CRT','SSL_PEM']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "eu.gcr.io/$PROJECT_ID/magento2-apache24:latest"]
images: ["eu.gcr.io/$PROJECT_ID/magento2-apache24"]

secrets:
- kmsKeyName: "projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver"
  secretEnv:
    SSL_KEY: CiQAwLhXnYlnR9B+OjcU1r49DF8VqzIQDgWEZayVwSYtzGjkCpASYADjhmPvdzQE1zmvxQTZA2scCqmWaiwNDZQtin0JfCpE+JxUmzK90+xlYcpcpCyD0s5LSYXQGRTzNqV4+5pno7+ERmfRPR7QLR4gbjRmzsGInQLmcyeFeNJwV/zmHh2pwg==
- kmsKeyName: "projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver-cert"
  secretEnv:
    SSL_CRT: CiQAw4sRuTHhD8HpGhA8bdQS8UYOrQZjKxDUkbZFC5OcMtPB5UsSYADRjCZ/IHa7n8G5kI5lEWob9CJbUfqcJw0g5OVEVkAjc5L2I8Rx93kijcs++H1oWn+yhdjYv0yT2EYB0n7W8Oje79p1ZCf79QSwAunhKgYFhccUsBUrHyY+QGQKSYTLaQ==
- kmsKeyName: "projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver-pem"
  secretEnv:
    SSL_PEM: CiQAmlC+DSjiaWEuPxB702MvQEM85cRXRM4Viw5JNrRTPmh6TNASXACJnZ61D477HH4U9jcJubu7pSXjumdXCHXZ9KdVtBgCV5lWJZaBoG4SAKK4seWiMNq+p/ZUm9+06MQGi7iVxTIdtRxMzCT3qtQrfn03hya4ZLjR9i4MwnbHqWrd
