steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker build -t eu.gcr.io/$PROJECT_ID/magento2-apache24:latest -f k8s-config/apache-docker/Dockerfile --build-arg WEB_SSL_CRT=$$SSL_CRT .'
    ]
  #secretEnv: ['SSL_KEY','SSL_CRT','SSL_PEM']
  secretEnv: ['SSL_CRT']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "eu.gcr.io/$PROJECT_ID/magento2-apache24:latest"]
images: ["eu.gcr.io/$PROJECT_ID/magento2-apache24"]

# echo -n $path_to_enc_file | gcloud kms encrypt --plaintext-file=- \
#   --ciphertext-file=- --location=global --keyring=$keyring-name \
#   --key=$key-name | base64
secrets:
- kmsKeyName: 'projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver-new-cert'
  secretEnv:
    SSL_CRT: CiQA4UGEtMvpbiB4cKzZyOyFQguOaWD8iBQO58eieEhMCjjEFeASPQDAa9sOajt17yThiBAY47DzCIOb8+Tw6wY0BLKZNfsgjnP3I78PsHIOS+GkU4C70UeQwUFEGnwi77NRPUc=