steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
   - kms
   - decrypt
   - --ciphertext-file=./mage.xyz.crt.enc1.new.txt
   - --plaintext-file=./mage.test.crt
   - --location=global
   - --keyring=magento-web-secrets
   - --key=magento-webserver-new-cert
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker build -t eu.gcr.io/$PROJECT_ID/magento2-apache24:latest -f k8s-config/apache-docker/Dockerfile .'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "eu.gcr.io/$PROJECT_ID/magento2-apache24:latest"]
images: ["eu.gcr.io/$PROJECT_ID/magento2-apache24"]