steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    #'docker build -t eu.gcr.io/$PROJECT_ID/magento2-apache24:latest -f k8s-config/apache-docker/Dockerfile --build-arg WEB_SSL_KEY=$$SSL_KEY --build-arg WEB_SSL_CRT=$$SSL_CRT --build-arg WEB_SSL_PEM=$$SSL_PEM .'
    'docker build -t eu.gcr.io/$PROJECT_ID/magento2-apache24:latest -f k8s-config/apache-docker/Dockerfile --build-arg WEB_SSL_CRT=$$SSL_CRT .'
    ]
  #secretEnv: ['SSL_KEY','SSL_CRT','SSL_PEM']
  secretEnv: ['SSL_CRT']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "eu.gcr.io/$PROJECT_ID/magento2-apache24:latest"]
images: ["eu.gcr.io/$PROJECT_ID/magento2-apache24"]

# echo -n $path_to_enc_file | gcloud kms encrypt --plaintext-file=- \
#   --ciphertext-file=- --location=global --keyring=$keyring-name \
#   --key=$key-name | base64
secrets:
# - kmsKeyName: "projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver"
#   secretEnv:
#     SSL_KEY: CiQAwLhXnYlnR9B+OjcU1r49DF8VqzIQDgWEZayVwSYtzGjkCpASYADjhmPvdzQE1zmvxQTZA2scCqmWaiwNDZQtin0JfCpE+JxUmzK90+xlYcpcpCyD0s5LSYXQGRTzNqV4+5pno7+ERmfRPR7QLR4gbjRmzsGInQLmcyeFeNJwV/zmHh2pwg==
- kmsKeyName: "projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver-cert"
  secretEnv:
    SSL_CRT: CiQAw4sRuXxpxmDZj7aQAZeITR6KwdFF7cJVYFxBpYPdsTeGEcES+wkA0YwmfyR8CXRuVgjlTA9FrU/tCLPW7QdZDZ/tR/Xr91yu0dIKZ5/0THC5oIBNvlmqXGRYwUZRjTrIIH4V5qUP16jCmc7nXec/mxmkDQmQxFDetVXGTDsp6
g6dl44W/AUdNCMsi1smI0T/v54pOAIFzpCT09U6mtkgTlO7mCDbaW0bHZskNXBtSod+5ZIdo1MySKZ08F1cXZkhMKyyKsdR9dnV8oVJctQhg+9uatYKUmwE3vpPf7naxJfY9cTJHkRNpwehujwkVetvr8TRFBnvmR8H6MFhib5Rem
BDT5apJu8IKAmhKyO5LD89VI8O3yq7b6R5Y/vmMBZ/iAVHZzGs5GVR0RSoIridzVSNNFeGenZHm7NZTmsbt+P9zL+y2wUD3KojwRdjYEpWeYjWI+8S+2ivPf9gRJuuwvw+6cWuo0UhjMlppeEDavbadMjcVo1NQq48BYJ54AQepYA
l/ZkAiBqEhOqTYydaIp9W+0C+V2Z3dBGodBqtJ/oOuvGRxeijqDhaWL2cK+0nSNSK5QXpljj1YVTKDOpmZSEWZQI6IOhm4GHCn80yXtLWG+8U2yxiUVKMK5wdYP7/+qqcbBwxYZ7dcF1rgdXQ8flYDAU4JfsJoRkNkeGAj1b4c+Mj
/EhBV1PiB4/5J0bus0xk15sn5Nx805k7LGs99I/C7x7QWUJEqINI3oNSvQBTDEnuKBdSUcokv0JIBOzoQ2cjuK3/Z4WXeYIZiugf0i1YxfvlmzR5gwZZJ2eI60zJvAQKufMHAqO9CwyfTKqiQa5F6m+2Rwu+yiQHdy1Z/pu4lbsi7
bb8P91WZBpNrwb+7KB6dk1BCE7+kykxfpqGLJXHBm81tgGirHXYxBpHru0CpfMZAVwMABBdgh+tY0K+OYUuxYT6sTDQ42m7PV2E5PjXJ19o3/a0zbqWO1Uo0J5BwbufQ2FODAJ4vnAl26UZ82QPNARBg/okJ6xmvJhhWVUrpqTOgz
jjV2NlwaeA/mZtkux8va6FREPJ8SSmt5AznHNTgWnxYQc0A5sgN8NsCm1vthHpgzcdGkrhutjJ7/5Chwt3UlgnUohduLLJr/aWZVlxnfRnqL9yON95Zf8bRUtyJdZxRXJUSuB3/9JjXnx4nQB4BHG280tCK2O2AdmORQ1KJe/vRh+
hIbvbprWS4fW78PRtzSQdo+GNWTcWWnk8eyIKkkxHRTPoXTbCT8rvvoC0FfVJobfWoGGOGRXLXPbMrA5QBtUhYP0ut+2Vq9fYxWilDm+wns6lnOsjAubagS9eRR+Q0qJFyPeyMuJnzNgTyccmiJauuFqelaKnmaPEcsSfjbapHzOY
5yQqr044HxDdEhWkjpjaKOI80OTdobPS+ztvjdygoNVunWuYisYyLEQS5lH7HGmNukZh5EhnqmiS2AlattKt3x0Myn6Y/RB7LjR3kEFQBNH8BBHEk9X0dIz8eWEbNtG6Eae3uUfaTFN7XB6BOTqS3ffMpL0F4JprG8pb39yuz3sKt
A3euODjvlrBX6NRSFdDGTxvXFKtSDuGnHnIJwKB+F4Z620SI+1Cs/+WzahF34zZhDgQoys5xtsAQmWG/ZpFihMbRjAzGQl684yslCiZzOMMtRrClJ+AYi4Nm3LO9zACVNXzXyQqhO4PAc4iPgFXrcRKaOeRGrA64hgBItLwvfriFR
DLeBVXqx442MC5u+OUYNJpssA=
# - kmsKeyName: "projects/magento2-269418/locations/global/keyRings/magento-web-secrets/cryptoKeys/magento-webserver-pem"
#   secretEnv:
#     SSL_PEM: CiQAmlC+DSjiaWEuPxB702MvQEM85cRXRM4Viw5JNrRTPmh6TNASXACJnZ61D477HH4U9jcJubu7pSXjumdXCHXZ9KdVtBgCV5lWJZaBoG4SAKK4seWiMNq+p/ZUm9+06MQGi7iVxTIdtRxMzCT3qtQrfn03hya4ZLjR9i4MwnbHqWrd
