version: "3.7"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data:delegated
    ports:
      - 9200:9200
    networks:
      - elastic
  php:
    image: php73:1
    build: 
      context: './docker/php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
      - elastic
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html:delegated
    container_name: php
  apache:
    image: apache24:1
    build:
      context: './docker/apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "443:443"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html:delegated
    environment:
      TZ: "Europe/London"
    container_name: apache
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
            - mysql:/var/lib/mysql:delegated
    networks:
      - backend
    environment:
      TZ: "Europe/London"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    container_name: magento-mysql
networks:
  frontend:
  backend:
  elastic:
    driver: bridge
volumes:
  mysql:
  data01:
    driver: local
