apiVersion: v1
kind: Secret
metadata:
  name: wwwmage-secret
type: kubernetes.io/tls
data:
  tls.crt: |
    !!REPLACE_WITH_WWWMAGESECRET_CRT!!
  tls.key: |
    !!REPLACE_WITH_WWWMAGESECRET_KEY!!
---
apiVersion: v1
kind: Secret
metadata:
  name: staticmage-secret
type: kubernetes.io/tls
data:
  tls.crt: |
    !!REPLACE_WITH_WWWMAGESECRET_CRT!!
  tls.key: |
    !!REPLACE_WITH_WWWMAGESECRET_KEY!!