apiVersion: v1
kind: Service
metadata:
  name: magento
  annotations:
    #cloud.google.com/app-protocols: '{"mage-https-port":"HTTPS", "mage-http-port":"HTTP"}'
    #cloud.google.com/app-protocols: '{"mage-https-port":"HTTPS","mage-http-port":"HTTP"}'
    cloud.google.com/backend-config: '{"ports": {"mage-https-port":"http-hc-config"}}'
    cloud.google.com/app-protocols: '{"mage-https-port":"HTTP2"}'
spec:
  type: NodePort
  selector:
    app: magento
  ports:
  - name: mage-https-port
    port: 443
    protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 3
    type: HTTP2
    requestPath: /healthz/
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: magento
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: magento
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: magento-ingress
  #annotations: 
  #  kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: wwwmage-secret
  - secretName: staticmage-secret
  rules:
  - host: www.mage.xyz
    http:
      paths:
      - backend:
          serviceName: magento
          servicePort: mage-https-port
  - host: static.mage.xyz
    http:
      paths:
      - backend:
          serviceName: magento
          servicePort: mage-https-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  labels:
    app: magento
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      securityContext:
        supplementalGroups:
          - 82
        fsGroup: 82
      initContainers:
        - name: setup-pub-dir
          image: eu.gcr.io/magento-295411/magento2-php72
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var
          command: ["/bin/sh"]
          args: 
            - -c
            - | 
              chmod -R 0777 /var/www/html/pub; 
              chmod -R 0775 /var/www/html/var; 
              chgrp -R 82 /var/www/html/pub /var/www/html/var; 
          resources:
            requests:
              cpu: "500m"
      containers:
        - image: eu.gcr.io/magento-295411/magento2-apache24
          name: apache
          ports:
            - containerPort: 443
              name: apache-port
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 80
            failureThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 3
            initialDelaySeconds: 0
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 80
            failureThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 3
            initialDelaySeconds: 1
        - image: eu.gcr.io/magento-295411/magento2-php72
          name: php
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "300m"
          livenessProbe:
            exec:
              command:
                - php-fpm-healthcheck
                - --listen-queue=20 # fails if there are more than 10 processes waiting in the fpm queue
            initialDelaySeconds: 0
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck # a simple ping since this means it's ready to handle traffic
            initialDelaySeconds: 1
            periodSeconds: 5
          ports:
            - containerPort: 9000
              name: php
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var   
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_HOSTNAME
              value: elasticsearch-es-http
      nodeSelector: 
        private-app-pool: web-app
      volumes:
      - name: magento-pub-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-1
      - name: magento-var-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-2
---
apiVersion: v1
kind: Secret
metadata:
  name: wwwmage-secret
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZVENDQWttZ0F3SUJBZ0lKQUs4YTc3djhLcWlvTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ0F4Q3pBSkJnTlYKQkFZVEFrZENNUkV3RHdZRFZRUUREQWh0WVdkbExuaDVlakFlRncweU1EQTJNall4T0RJMU1qbGFGdzB5TWpBNQpNamt4T0RJMU1qbGFNQk14RVRBUEJnTlZCQU1NQ0cxaFoyVXVlSGw2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeDJnejRadU1sTmF1YkhPRlMxSzMyQjRINUZ2QWoyWW1VNFJlZE9MRXlqRzMKMExlbzdFazFEcWh2WEh2UHNCVG9tUkhhZ1RKdkl2dFk2VXltSG9USXBzdUgwMmVoQm5Kcm5vVlhxUjZ0blA1VQowTDJEd3A1bExLaEVHaGZxMmhLS3RSUGJHV1pqOUlQd3hZYlJ0Rk5ReHNUWnNhWWlHNEdPTndINnVJMHJONE9WCkhMbFZzRzlBMDBFZE9RSEZaQWgxb2h1Qmc1UHhDOXJCZHF3WFhSSEY1QlZYYVB2bjRidW9Xa3pHMWFvczJySWwKTkU2aGZFV0tBbldPWGEwQVZRUW9ySnkzMUFPdnlScTFtWFM4MG9qbFJ3UVByKzJzVkVRTWRjNXZMTGxkc2NRUwpveFE2U3Z4M282RkJaUXhMTnVzRW8reDZXV2owQ084S2x0L3R4NmJjUVFJREFRQUJvNEdxTUlHbk1Eb0dBMVVkCkl3UXpNREdoSktRaU1DQXhDekFKQmdOVkJBWVRBa2RDTVJFd0R3WURWUVFEREFodFlXZGxMbmg1ZW9JSkFNRUgKWXZEcDRyWUNNQWtHQTFVZEV3UUNNQUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQwpNQXNHQTFVZER3UUVBd0lFOERBeUJnTlZIUkVFS3pBcGdnaHRZV2RsTG5oNWVvSU1kM2QzTG0xaFoyVXVlSGw2CmdnOXpkR0YwYVdNdWJXRm5aUzU0ZVhvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLUHhJMjFlNEJFNituWU8KajVSUU52dEdycXNtcUlueDc2TXdKM0hHSkJsRmN6QkRuamQzN3RIRjgyNFNuenVabjlITklIL2hKRW10WCtmZwpUV1lQdWRJOEs4Z1NFUk5tc09QZEhsSC8wUWYzbVl0ck5KNlNJRGZKc1lZMjZQbU1Ob2p0bi9WUVRPbDdzZU12Ck9WYlJUV0hXZktmcytUVE9nWFo4cTUrZDJiMFpIQksxZHM1ZGd0eFc2ekw4T3V2NzFjVzBDRWhSR3JsU2l3RU0KNTZMNzA4SVBFcDdpeEY0cVN1aE9oVXNjZGlBUFJzZFNyQ2x6MElDTXZGTUFnWjJodjdSeFhtZ004TnhJWnJlbQo1b2c3emlSejJNWUlDSWlhSEcxUkFvUzllZjZnRkU0SzJoRHNuMHY5RGR4bVYrcFNqWUhicG0vZlorWTZnUWI1ClhmVktxNGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dEQ0NBVUFDQVFBd0V6RVJNQThHQTFVRUF3d0liV0ZuWlM1NGVYb3dnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREhhRFBobTR5VTFxNXNjNFZMVXJmWUhnZmtXOENQWmlaVGhGNTA0c1RLCk1iZlF0NmpzU1RVT3FHOWNlOCt3Rk9pWkVkcUJNbThpKzFqcFRLWWVoTWlteTRmVFo2RUdjbXVlaFZlcEhxMmMKL2xUUXZZUENubVVzcUVRYUYrcmFFb3ExRTlzWlptUDBnL0RGaHRHMFUxREd4Tm14cGlJYmdZNDNBZnE0alNzMwpnNVVjdVZXd2IwRFRRUjA1QWNWa0NIV2lHNEdEay9FTDJzRjJyQmRkRWNYa0ZWZG8rK2ZodTZoYVRNYlZxaXphCnNpVTBUcUY4UllvQ2RZNWRyUUJWQkNpc25MZlVBNi9KR3JXWmRMelNpT1ZIQkErdjdheFVSQXgxem04c3VWMngKeEJLakZEcEsvSGVqb1VGbERFczI2d1NqN0hwWmFQUUk3d3FXMyszSHB0eEJBZ01CQUFHZ0FEQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBQnB0UnRoZ1ZWZnd5MzNWM3RKbVVsNlF4QUJsSlpXRHJWVG9HTUpSQVkxdkp5U3RECjBHcTFBWS9SMEpDTjI5WmV1VjFaUVc5dHdVLzNaUzRONHlmQktWL0dIM1lzYnBEOUFwV0pPRXFTMG9JN3Fya0EKUHpSOVYzcno4Vk5EcXpVL1g2UnBoT004Ym5MS3I5VHFzN2hESkdYdWdrSlRjRjVDSTZYN1JPT3F2dTBZVHVJSQpKalB5M3hXdlNCNEVBWGlpcVNEUUxZN3VRY3ZOaThkU0NHUlAwSXZ6QnlsMk9kUEtIUjBjbjRvRG14dVI5a290CjhRU2hhU0VFQ2lIR3hadGtOV3o2THhEVnFPOHFQWW9nRmVUSlpZUHhXM0VOdk4xTU5YMUpUa3RWTnBpQ3hPZ0oKUFRnTWMzOGtpZlpiZlAxUzdtTlpGekRqL2xxNDQrYngrUFUwaGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeDJnejRadU1sTmF1YkhPRlMxSzMyQjRINUZ2QWoyWW1VNFJlZE9MRXlqRzMwTGVvCjdFazFEcWh2WEh2UHNCVG9tUkhhZ1RKdkl2dFk2VXltSG9USXBzdUgwMmVoQm5Kcm5vVlhxUjZ0blA1VTBMMkQKd3A1bExLaEVHaGZxMmhLS3RSUGJHV1pqOUlQd3hZYlJ0Rk5ReHNUWnNhWWlHNEdPTndINnVJMHJONE9WSExsVgpzRzlBMDBFZE9RSEZaQWgxb2h1Qmc1UHhDOXJCZHF3WFhSSEY1QlZYYVB2bjRidW9Xa3pHMWFvczJySWxORTZoCmZFV0tBbldPWGEwQVZRUW9ySnkzMUFPdnlScTFtWFM4MG9qbFJ3UVByKzJzVkVRTWRjNXZMTGxkc2NRU294UTYKU3Z4M282RkJaUXhMTnVzRW8reDZXV2owQ084S2x0L3R4NmJjUVFJREFRQUJBb0lCQUVZR0c2SHdJNi9vcTV1OQovV0wwQzBkRFZIWW1tanBCSHRoWk5XcEtiOXlwRk9tZ2RSdDBvY01oOXVrOU9UT1dSQS9zcXhTUGgyTjdiRCtSCkFRemFpRE82YVZvZG0vaE5tZWt5M2hPdmlEd0hPL1dKZDRtU1lla0t0YytMOHBiZHlBUEtremdhTXFPYzZhSVQKcy9SbEJZcW5lZUxlZWorNmdSeGovNDFyVlcvS2tJMzBESXcrNzI4TFdTWDd3a0MvSTJWOU5IRGFwSmJLL0p6VwpxSlM0QTdYWi9obWxXancvc0VSUm9pVEZZRUFqcms4anAxTUdsUlV5dXBML2pVTFJMT3h4L1JxVi9sZUdYK2E0CkFLQ2VTeThFKzIvTDB6bWMyc2FubmlqWWVqbHY1ZUs4NHA1OGZieG5heGNkL2NLR1VrRS9xczM1VlBHczM5SVAKTmNQU25Ca0NnWUVBNWtydi8zZlhPclBoYzRXSEhGNFViWkV3UmhiOGVveDVyZE9SaEFUM3JnUmNvMFQ2ckM1NQp1MEo4ZjN0MEZmby9EKzVrRkN0ZmFNSVdocEJRN0gwckllcUZUVFhiZ1pQMnU1V3lLcXY0TGw3T3FoM0hBZnFjCkVic2ZPQXR6a0d5cFZ0d3RRSU04bTBjZFVQMXJZWmFtZ0JwbDMwU2d5UWFzWXdlbk9WTi8xUWNDZ1lFQTNhcWwKanJuYlIvbVJHQ1R1TUNBcTJPckNEWmdTdUNJcTZUeFVTcVdWTHRXclJFNnVhR0NXV1ZrekdLRGxlZGFZUU41bQpXbTNHNm1vSzVNUURyNTFtTUVhaGdybytQVkdob3NzQ0dDT3ZaVSsrN0xiNmcrOXlVSVU0UC9UK1R5eE1HNXlECk5CNm9UR09Ud3picXlVWFBJZFNpTnRFRDJPMWZSU3ZnTDBxKytuY0NnWUJBQzRNbk52cmlWbmhTbWtYeSs2OE8Kc1p3TlFnTkJTYVBsVmJ0WVRkRmIwZGE1aVV0MWF3OXJwcGZkRkVZNmZuZmZSRnNNeU9zbHhTUmlrK3dOZU5udgorcnJMdURpdGxxcTlqR29hTiswemFDWnRaUTZkWEViZkgzMFZKd29pbGpXWjlHMlpUV1lqZ09tRVJwWUFjOWNtCk5URXpvSEJldDc1bFpCRjdmZDlGTFFLQmdHa21PY0txaDBwdEtGYTdyZ0ZHUVEwRXoyaURhdDNOMTIwc0lSQUgKMit5TGp1S29NRE56SGQ3a1lVaWRpajF4Zm1mSEYrWnRqSjVHRDBUVmRxb25rQUgyZjBiejhmSkVkdGd5Vkp2KwowWVROZjFQcXVJczlXb3kzcFNjeG9ERU9Za3Yyd29aR3hLNzN6WEFjN09MdEtvUnh5VUVYaFN1eDdpOXgwTGFlClRsbWhBb0dBTjBXUkZKTk56WTNiL25YR3FqUVBwVFNEd2dEMjRUQWtMbHgwNmY4TnhLazVHRHFxOWcvQWJDeTEKZUdQcGFQK05KUXYvZy84QTk0V0p4c0JuaW83blY3cWNDR21BL2lXM0FSa1VjRm50T0Y5SkpNMC9LU25IWUR5dApYQlgxVFdiZk9LUW5hUGtoTmtHRS9oZCtEVW9oQjE5cjk0K3RrYzBBQ0JUTkozK0k2Z0U9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: staticmage-secret
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZVENDQWttZ0F3SUJBZ0lKQUs4YTc3djhLcWlvTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ0F4Q3pBSkJnTlYKQkFZVEFrZENNUkV3RHdZRFZRUUREQWh0WVdkbExuaDVlakFlRncweU1EQTJNall4T0RJMU1qbGFGdzB5TWpBNQpNamt4T0RJMU1qbGFNQk14RVRBUEJnTlZCQU1NQ0cxaFoyVXVlSGw2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeDJnejRadU1sTmF1YkhPRlMxSzMyQjRINUZ2QWoyWW1VNFJlZE9MRXlqRzMKMExlbzdFazFEcWh2WEh2UHNCVG9tUkhhZ1RKdkl2dFk2VXltSG9USXBzdUgwMmVoQm5Kcm5vVlhxUjZ0blA1VQowTDJEd3A1bExLaEVHaGZxMmhLS3RSUGJHV1pqOUlQd3hZYlJ0Rk5ReHNUWnNhWWlHNEdPTndINnVJMHJONE9WCkhMbFZzRzlBMDBFZE9RSEZaQWgxb2h1Qmc1UHhDOXJCZHF3WFhSSEY1QlZYYVB2bjRidW9Xa3pHMWFvczJySWwKTkU2aGZFV0tBbldPWGEwQVZRUW9ySnkzMUFPdnlScTFtWFM4MG9qbFJ3UVByKzJzVkVRTWRjNXZMTGxkc2NRUwpveFE2U3Z4M282RkJaUXhMTnVzRW8reDZXV2owQ084S2x0L3R4NmJjUVFJREFRQUJvNEdxTUlHbk1Eb0dBMVVkCkl3UXpNREdoSktRaU1DQXhDekFKQmdOVkJBWVRBa2RDTVJFd0R3WURWUVFEREFodFlXZGxMbmg1ZW9JSkFNRUgKWXZEcDRyWUNNQWtHQTFVZEV3UUNNQUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQwpNQXNHQTFVZER3UUVBd0lFOERBeUJnTlZIUkVFS3pBcGdnaHRZV2RsTG5oNWVvSU1kM2QzTG0xaFoyVXVlSGw2CmdnOXpkR0YwYVdNdWJXRm5aUzU0ZVhvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLUHhJMjFlNEJFNituWU8KajVSUU52dEdycXNtcUlueDc2TXdKM0hHSkJsRmN6QkRuamQzN3RIRjgyNFNuenVabjlITklIL2hKRW10WCtmZwpUV1lQdWRJOEs4Z1NFUk5tc09QZEhsSC8wUWYzbVl0ck5KNlNJRGZKc1lZMjZQbU1Ob2p0bi9WUVRPbDdzZU12Ck9WYlJUV0hXZktmcytUVE9nWFo4cTUrZDJiMFpIQksxZHM1ZGd0eFc2ekw4T3V2NzFjVzBDRWhSR3JsU2l3RU0KNTZMNzA4SVBFcDdpeEY0cVN1aE9oVXNjZGlBUFJzZFNyQ2x6MElDTXZGTUFnWjJodjdSeFhtZ004TnhJWnJlbQo1b2c3emlSejJNWUlDSWlhSEcxUkFvUzllZjZnRkU0SzJoRHNuMHY5RGR4bVYrcFNqWUhicG0vZlorWTZnUWI1ClhmVktxNGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dEQ0NBVUFDQVFBd0V6RVJNQThHQTFVRUF3d0liV0ZuWlM1NGVYb3dnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREhhRFBobTR5VTFxNXNjNFZMVXJmWUhnZmtXOENQWmlaVGhGNTA0c1RLCk1iZlF0NmpzU1RVT3FHOWNlOCt3Rk9pWkVkcUJNbThpKzFqcFRLWWVoTWlteTRmVFo2RUdjbXVlaFZlcEhxMmMKL2xUUXZZUENubVVzcUVRYUYrcmFFb3ExRTlzWlptUDBnL0RGaHRHMFUxREd4Tm14cGlJYmdZNDNBZnE0alNzMwpnNVVjdVZXd2IwRFRRUjA1QWNWa0NIV2lHNEdEay9FTDJzRjJyQmRkRWNYa0ZWZG8rK2ZodTZoYVRNYlZxaXphCnNpVTBUcUY4UllvQ2RZNWRyUUJWQkNpc25MZlVBNi9KR3JXWmRMelNpT1ZIQkErdjdheFVSQXgxem04c3VWMngKeEJLakZEcEsvSGVqb1VGbERFczI2d1NqN0hwWmFQUUk3d3FXMyszSHB0eEJBZ01CQUFHZ0FEQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBQnB0UnRoZ1ZWZnd5MzNWM3RKbVVsNlF4QUJsSlpXRHJWVG9HTUpSQVkxdkp5U3RECjBHcTFBWS9SMEpDTjI5WmV1VjFaUVc5dHdVLzNaUzRONHlmQktWL0dIM1lzYnBEOUFwV0pPRXFTMG9JN3Fya0EKUHpSOVYzcno4Vk5EcXpVL1g2UnBoT004Ym5MS3I5VHFzN2hESkdYdWdrSlRjRjVDSTZYN1JPT3F2dTBZVHVJSQpKalB5M3hXdlNCNEVBWGlpcVNEUUxZN3VRY3ZOaThkU0NHUlAwSXZ6QnlsMk9kUEtIUjBjbjRvRG14dVI5a290CjhRU2hhU0VFQ2lIR3hadGtOV3o2THhEVnFPOHFQWW9nRmVUSlpZUHhXM0VOdk4xTU5YMUpUa3RWTnBpQ3hPZ0oKUFRnTWMzOGtpZlpiZlAxUzdtTlpGekRqL2xxNDQrYngrUFUwaGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeDJnejRadU1sTmF1YkhPRlMxSzMyQjRINUZ2QWoyWW1VNFJlZE9MRXlqRzMwTGVvCjdFazFEcWh2WEh2UHNCVG9tUkhhZ1RKdkl2dFk2VXltSG9USXBzdUgwMmVoQm5Kcm5vVlhxUjZ0blA1VTBMMkQKd3A1bExLaEVHaGZxMmhLS3RSUGJHV1pqOUlQd3hZYlJ0Rk5ReHNUWnNhWWlHNEdPTndINnVJMHJONE9WSExsVgpzRzlBMDBFZE9RSEZaQWgxb2h1Qmc1UHhDOXJCZHF3WFhSSEY1QlZYYVB2bjRidW9Xa3pHMWFvczJySWxORTZoCmZFV0tBbldPWGEwQVZRUW9ySnkzMUFPdnlScTFtWFM4MG9qbFJ3UVByKzJzVkVRTWRjNXZMTGxkc2NRU294UTYKU3Z4M282RkJaUXhMTnVzRW8reDZXV2owQ084S2x0L3R4NmJjUVFJREFRQUJBb0lCQUVZR0c2SHdJNi9vcTV1OQovV0wwQzBkRFZIWW1tanBCSHRoWk5XcEtiOXlwRk9tZ2RSdDBvY01oOXVrOU9UT1dSQS9zcXhTUGgyTjdiRCtSCkFRemFpRE82YVZvZG0vaE5tZWt5M2hPdmlEd0hPL1dKZDRtU1lla0t0YytMOHBiZHlBUEtremdhTXFPYzZhSVQKcy9SbEJZcW5lZUxlZWorNmdSeGovNDFyVlcvS2tJMzBESXcrNzI4TFdTWDd3a0MvSTJWOU5IRGFwSmJLL0p6VwpxSlM0QTdYWi9obWxXancvc0VSUm9pVEZZRUFqcms4anAxTUdsUlV5dXBML2pVTFJMT3h4L1JxVi9sZUdYK2E0CkFLQ2VTeThFKzIvTDB6bWMyc2FubmlqWWVqbHY1ZUs4NHA1OGZieG5heGNkL2NLR1VrRS9xczM1VlBHczM5SVAKTmNQU25Ca0NnWUVBNWtydi8zZlhPclBoYzRXSEhGNFViWkV3UmhiOGVveDVyZE9SaEFUM3JnUmNvMFQ2ckM1NQp1MEo4ZjN0MEZmby9EKzVrRkN0ZmFNSVdocEJRN0gwckllcUZUVFhiZ1pQMnU1V3lLcXY0TGw3T3FoM0hBZnFjCkVic2ZPQXR6a0d5cFZ0d3RRSU04bTBjZFVQMXJZWmFtZ0JwbDMwU2d5UWFzWXdlbk9WTi8xUWNDZ1lFQTNhcWwKanJuYlIvbVJHQ1R1TUNBcTJPckNEWmdTdUNJcTZUeFVTcVdWTHRXclJFNnVhR0NXV1ZrekdLRGxlZGFZUU41bQpXbTNHNm1vSzVNUURyNTFtTUVhaGdybytQVkdob3NzQ0dDT3ZaVSsrN0xiNmcrOXlVSVU0UC9UK1R5eE1HNXlECk5CNm9UR09Ud3picXlVWFBJZFNpTnRFRDJPMWZSU3ZnTDBxKytuY0NnWUJBQzRNbk52cmlWbmhTbWtYeSs2OE8Kc1p3TlFnTkJTYVBsVmJ0WVRkRmIwZGE1aVV0MWF3OXJwcGZkRkVZNmZuZmZSRnNNeU9zbHhTUmlrK3dOZU5udgorcnJMdURpdGxxcTlqR29hTiswemFDWnRaUTZkWEViZkgzMFZKd29pbGpXWjlHMlpUV1lqZ09tRVJwWUFjOWNtCk5URXpvSEJldDc1bFpCRjdmZDlGTFFLQmdHa21PY0txaDBwdEtGYTdyZ0ZHUVEwRXoyaURhdDNOMTIwc0lSQUgKMit5TGp1S29NRE56SGQ3a1lVaWRpajF4Zm1mSEYrWnRqSjVHRDBUVmRxb25rQUgyZjBiejhmSkVkdGd5Vkp2KwowWVROZjFQcXVJczlXb3kzcFNjeG9ERU9Za3Yyd29aR3hLNzN6WEFjN09MdEtvUnh5VUVYaFN1eDdpOXgwTGFlClRsbWhBb0dBTjBXUkZKTk56WTNiL25YR3FqUVBwVFNEd2dEMjRUQWtMbHgwNmY4TnhLazVHRHFxOWcvQWJDeTEKZUdQcGFQK05KUXYvZy84QTk0V0p4c0JuaW83blY3cWNDR21BL2lXM0FSa1VjRm50T0Y5SkpNMC9LU25IWUR5dApYQlgxVFdiZk9LUW5hUGtoTmtHRS9oZCtEVW9oQjE5cjk0K3RrYzBBQ0JUTkozK0k2Z0U9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==