apiVersion: v1
kind: Service
metadata:
  name: magento-canary
  annotations:
    #cloud.google.com/app-protocols: '{"mage-https-port":"HTTPS", "mage-http-port":"HTTP"}'
    #cloud.google.com/app-protocols: '{"mage-https-port":"HTTPS","mage-http-port":"HTTP"}'
    cloud.google.com/backend-config: '{"ports": {"mage-https-port":"http-hc-config"}}'
    cloud.google.com/app-protocols: '{"mage-https-port":"HTTP2"}'
spec:
  type: NodePort
  selector:
    app: magento-canary
  ports:
  - name: mage-https-port
    port: 443
    protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 3
    type: HTTP2
    requestPath: /healthz/
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: magento-canary-ingress
  #annotations: 
  #  kubernetes.io/ingress.class: istio
spec:
  tls:
  - secretName: wwwmage-secret
  - secretName: staticmage-secret
  rules:
  - host: www.mage.xyz
    http:
      paths:
      - backend:
          serviceName: magento-canary
          servicePort: mage-https-port
  - host: static.mage.xyz
    http:
      paths:
      - backend:
          serviceName: magento-canary
          servicePort: mage-https-port