apiVersion: v1
kind: Service
metadata:
  name: magento-mysql
  labels:
    app: magento-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: magento-mysql
    tier: mysql
  clusterIP: None
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
  labels:
    app: magento-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-mysql
  labels:
    app: magento-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento-mysql
        tier: mysql
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - image: percona:5.7
          name: mysql
          args:
            - "--ignore-db-dir=lost+found"
          envFrom:
          - secretRef:
              name: mysql-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      nodeSelector: 
        private-db-pool: mysql-db
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: bWFnZW50bw==
  MYSQL_ROOT_PASSWORD: bWFnZW50bw==