apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: magento-canary
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: magento-canary
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-canary
  labels:
    app: magento-canary
    version: next
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: magento-canary
      version: next
  template:
    metadata:
      labels:
        app: magento-canary
        version: next
        stack: canary
    spec:
      securityContext:
        supplementalGroups:
          - 82
        fsGroup: 82
      initContainers:
        - name: setup-pub-dir
          image: eu.gcr.io/magento-295411/magento2-php72:v1.0.67
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var
          command: ["/bin/sh"]
          args: 
            - -c
            - | 
              chmod -R 0777 /var/www/html/pub; 
              chmod -R 0775 /var/www/html/var; 
              chgrp -R 82 /var/www/html/pub /var/www/html/var; 
          resources:
            requests:
              cpu: "500m"
      containers:
        - image: eu.gcr.io/magento-295411/magento2-apache24:latest
          name: apache
          ports:
            - containerPort: 443
              name: apache-port
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 80
            failureThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 3
            initialDelaySeconds: 0
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 80
            failureThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 3
            initialDelaySeconds: 1
        - image: eu.gcr.io/magento-295411/magento2-php72:v1.0.67
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/var/www/html/post.sh"]
          name: php
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "300m"
          livenessProbe:
            exec:
              command:
                - php-fpm-healthcheck
                - --listen-queue=20 # fails if there are more than 10 processes waiting in the fpm queue
            initialDelaySeconds: 0
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck # a simple ping since this means it's ready to handle traffic
            initialDelaySeconds: 1
            periodSeconds: 5
          ports:
            - containerPort: 9000
              name: php
          volumeMounts:
          - mountPath: /var/www/html/pub
            name: magento-pub-volume
            subPath: pub
          - mountPath: /var/www/html/var
            name: magento-var-volume
            subPath: var   
          env:
            - name: REPLICA_TYPE
              value: CANARY
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_HOSTNAME
              value: elasticsearch-es-http
      nodeSelector: 
        private-app-pool: web-app
      volumes:
      - name: magento-pub-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-1
      - name: magento-var-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-2