name: CI Build
on:
  pull_request:
    branches: [ development ]

jobs:
  build:
    name: QA Operations
    strategy:
      matrix:
        php: [7.3.17]
        node: [12.9.0]
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-fpm-alpine
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run composer install
      run: |
        composer install
    - name: Run QA script
      run: |
        sh ./run-qa.sh